# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 395551b51d693562fededbcd5d3a47efec2996d942c9f3e1754aabd8d4ba2bff3ab60289bad023e8f19d7058bf8dacc071a4f8928068b59630289fb16dbe9d03

test:
  secret_key_base: 803325ddb012c525980a15d1b841a05bbf26ac87368350181d6a9b1e024b88e4cc67db62750f15c815c6d9c97ec5e08d28b8b2799e8fda180708dfc933f0d544

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
